gone_front_end:
    resource: "@GoneFrontEndBundle/Resources/config/routing.yml"
    prefix:   /

gone_api:
    type: rest
    resource: "@GoneAPIBundle/Resources/config/routing.yml"
    prefix:   /

