parameters:
#    gone_front_end.example.class: Gone\FrontEndBundle\Example

services:
#    gone_front_end.example:
#        class: %gone_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
